name: Unity Test

on: 
  push:

  pull_request:
    branches:
      - main

  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Build and run tests
        run: |
          cd tests/
          gcc *.c  ../canscribe.c -I ..  -o test
          ./test
